### PR TITLE
Use an official NGINX image as a baseline

### PR DESCRIPTION
**Pull request by mlech-reef**

### CODE REVIEW

**Comment by wbancer-reef** [comment]
Have you changed anything from official nginx build then?
Maybe it's worth to use original build as FROM rather than forking instructions and building image by yourself?

**Comment by mlech-reef** [comment]
> Have you changed anything from official nginx build then? Maybe it's worth to use original build as FROM rather than forking instructions and building image by yourself?

Original nginx (nginx:1.24.0-alpine) is used in FROM. The rest is for installing additional nginx components and it is based on an example from the official repo - https://github.com/nginxinc/docker-nginx/tree/master/modules

**Comment by mlech-reef** [comment]
And also I had to tweak it for `certbot-nginx`

**Comment by wbancer-reef** [comment]
> > Have you changed anything from official nginx build then? Maybe it's worth to use original build as FROM rather than forking instructions and building image by yourself?
> 
> Original nginx (nginx:1.24.0-alpine) is used in FROM. The rest is for installing additional nginx components and it is based on an example from the official repo - https://github.com/nginxinc/docker-nginx/tree/master/modules

Ok, approved then :)

**Review by wbancer-reef — APPROVED** [review]

**Pull request merged**
